[package]
name = "bouncing-balls"
version = "0.1.0"
edition = "2021"

[dependencies]
marmalade = { path = "../../" }
console_error_panic_hook = "0.1.7"
glam = "0.29.2"
wasm-bindgen-futures = "0.4.50"
